language: csharp
solution: NUnit.Tests1.sln
install:
  - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./NUnit.Tests1.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Unit.Tests1.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NUnit.Tests1/bin/Release/NUnit.Tests1.dll